spring:
  datasource:
    url: jdbc:postgresql://db-news:5432/clevertec
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: liquibase/db.changelog-master.yml
  cache:
    type: redis
  data:
    redis:
      host: redis-cache
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
server:
  port: 8090
urls:
  userservice_url: http://user-service:8081/
aop:
  logging:
    enabled: true
exception:
  handling:
    enabled: true