version: '3.1'

volumes:
  cache:
    driver: local

services:
  redis:
    image: redis:7.2.3-alpine
    restart: always
    container_name: redis_dev
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass cGFzc3dvcnRvcmVkaXM=
    volumes:
      - cache:/data